로그인, 회원가입, 스플래쉬, MyTeacherInfo(TeacherSingleton) 추가
dohun94/dictation_teacher pull request #1
Opened 2017-09-27 06:55 UTC by dohun94

develope에 merge하기 전에 PR 날려봅니다.

2017-09-27 14:59 UTC, hmu332233 commented
근데 저 이미지 파일 저작권 걸릴텐데 이렇게 막 올리면

2017-10-07 11:48 UTC, dohun94 commented on app/src/main/java/com/blackdog/dictation_teacher/Activity/SplashActivity.java
> +            loginTask = new AsyncTask<Void, Void, Boolean>() {
로그인 요청 메서드가 다 끝난 후에  onPostExcute()에서 다음 액티비티가 로딩되도록 변경

2017-10-07 11:56 UTC, dohun94 commented on app/src/main/java/com/blackdog/dictation_teacher/Activity/SplashActivity.java
> +            loginTask = new AsyncTask<Void, Void, Boolean>() {
근데 이거 내가 보여주고싶은 범위 지정이 안되는데 어케하냐

2017-10-07 14:41 UTC, hmu332233 commented on app/src/main/java/com/blackdog/dictation_teacher/Activity/SplashActivity.java
> +            loginTask = new AsyncTask<Void, Void, Boolean>() {
보여주고 싶은거 범위 지정?은 github 자체에서는 안될거같은데 
그냥 우리끼리 표기할수있는 방법을 정하면 될듯
뭐 그 함수에 정의한곳에 가서 한다던가

2017-10-07 18:23 UTC, hmu332233 reviewed
일단은 머지하고 추후에 수정하는걸로!

2017-10-07 18:28 UTC, hmu332233 approved these changes
test용 입니다

2017-10-07 18:28 UTC, hmu332233 commented on app/build.gradle
> +
test

2017-10-07 18:28 UTC, hmu332233 commented on app/build.gradle
>      compile 'com.squareup.retrofit2:converter-gson:2.3.0'
test2

2017-10-07 18:28 UTC, hmu332233 commented on app/build.gradle
>      compile 'com.shawnlin:number-picker:2.4.4'
test3

2017-10-07 18:28 UTC, hmu332233 requested changes
test용입니다

2017-10-07 18:29 UTC, hmu332233 submitted a review, later dismissed

2017-10-07 18:32 UTC, hmu332233 commented
@dohun94 코드에 대해 싱글 코멘트를 달수도있고  
이렇게 리뷰라는 걸로 하나로 묶어서 할 수도 있는군
리뷰 종류가 여러개인데
둘 이상이서 테스트를 한번 해봐야겠당

2017-10-08 06:32 UTC, merged